site_name: Termodinámica

theme:
  name: readthedocs
#  name: material
#  highlightjs: true


nav:
  - Introducción:
    - ¿Qué es la termodinámica?: index.md
    - Distribución continua de la materia: distribucion_continua_materia.md
    - Conceptos: conceptos.md
    - Propiedades:
      - Introducción: propiedades.md
      - Presión: presion.md
      - Densidad y volumen específico: densidad.md
      - Temperatura (Principio Cero): temperatura.md
    - Estado: estado.md
    - Proceso: proceso.md
    - Fase: fase.md
    - Equilibrio: equilibrio.md
    - Alcance de la termodinámica: alcance_termodinamica.md

  - Primera Ley de la Termodinámica:
    - Resumen: 1st_resumen.md
    - Introducción: 1st_intro.md
    - Postulado de Estado - Sistemas simples: 1st_postulado_de_estado.md
    - Aplicaciones:
        - Sistemas Cerrados: 1st_sistemas_cerrados.md
        - Ciclos:
            - Carnot: 1st_ciclo_carnot.md



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
- admonition
- codehilite
- pymdownx.details
- pymdownx.superfences
- pymdownx.arithmatex
- mdx_math:
    enable_dollar_delimiter: true

plugins:
- search
